#!/usr/bin/env python

def install_action():
    pass

def help_action(action=None):
    pass

def available_actions():
    return [(a[:-7], f) for (a,f) in globals().items() 
                if type(f).__name__ == 'function' and a[-6:] == 'action']

if __name__ == "__main__":
    print available_actions()
